
name: Xpu3.0-Build-And-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  xpu-build-and-test:
    runs-on: xpu3.0
    if: ${{ github.repository == 'FlagTree/flagtree' || github.repository == 'flagos-ai/flagtree' }}
    steps:
      - name: Setup environment
        shell: bash
        run: |
          source ~/env.sh
          env | grep -E '^(http_proxy|https_proxy|all_proxy|no_proxy)=' >> $GITHUB_ENV || true

      - name: Smart Checkout
        uses: flagos-ai/FlagTree/.github/actions/smart-checkout@main
        with:
          checkout_version: 'v6'

      - name: Check if backend-relevant files changed
        id: check_backend
        uses: flagos-ai/FlagTree/.github/actions/check-backend-changed@main
        with:
          backend: xpu

      - name: FlagTree Build on Xpu
        if: steps.check_backend.outputs.should_skip != 'true'
        shell: bash
        run: |
          set -x
          pip uninstall -y triton
          export FLAGTREE_BACKEND=xpu
          cd python
          MAX_JOBS=32 python3 -m pip install . --no-build-isolation

      - name: FlagTree Test on Xpu
        if: steps.check_backend.outputs.should_skip != 'true'
        shell: bash
        run: |
          set -x
          export XPU_EVENT_KL3_ENABLE=1
          python3 -m pytest -s third_party/xpu/python/test/unit
